backend:
  name: git-gateway
  branch: main

media_folder: "Photography/Uploads"
public_folder: "/Photography/Uploads"

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  # 1. СТРАНИЦИ (Home Page)
  - name: "pages"
    label: "Настройки на Начална страница"
    files:
      - name: "home"
        label: "Начална страница (Home)"
        file: "data/home.json"
        fields:
          - {label: "Заглавие (Hero)", name: "hero_title", widget: "string", default: "Най-разглеждани"}

  # 2. ФОТОГРАФИЯ (Албуми)
  - name: "albums"
    label: "Фото Албуми"
    files:
      - name: "albums"
        label: "Списък албуми"
        file: "data.json"
        label_singular: "Албум"
        fields:
          - label: "Албуми"
            name: "albums"
            widget: "list"
            summary: "{{title}}"
            fields:
              - {label: "ID (URL Name)", name: "id", widget: "string", hint: "напр. djamala (на латиница)"}
              - {label: "Заглавие", name: "title", widget: "string"}
              - {label: "Корица", name: "cover", widget: "image"}
              - label: "Галерия снимки"
                name: "photos"
                widget: "list"
                fields:
                  - {label: "Снимка", name: "image", widget: "image"}
